[platformio]
src_dir = main

[env:m5stack_basic_v27]
platform = espressif32
framework = espidf
board = m5stack-core-esp32-16M
monitor_speed = 115200
upload_port = /dev/cu.usbserial-6D52ACA6E7
upload_speed = 115200
